#!/usr/bin/sh

export CUDA_CACHE_PATH=$XDG_CACHE_HOME/nv
export GNUPGHOME=$XDG_CONFIG_HOME/gnupg
export GOPATH=$XDG_DATA_HOME/go
export HISTCONTROL=ignoreboth
export HISTFILE=$XDG_CACHE_HOME/bash/history
export JAVA_HOME=/usr/lib/jvm/default
export LESSHISTFILE="-"
export MANPAGER='nvim +Man!'
export MANWIDTH=999
export MAVEN_HOME=/opt/maven
export GDBHISTFILE=$XDG_DATA_HOME/gdb/history
export PASSWORD_STORE_DIR=$XDG_DATA_HOME/pass

# removing the `.nv` directory from the home directory (see https://bbs.archlinux.org/viewtopic.php?id=166814):
export __GL_SHADER_DISK_CACHE_PATH=$XDG_DATA_HOME/nvidia

export CARGO_HOME=$XDG_DATA_HOME/cargo
export PATH="$CARGO_HOME/bin:$PATH"

export GEM_HOME=$XDG_DATA_HOME/ruby/gem
export PATH="$GEM_HOME/bin:$PATH"

export NODE_HOME=$XDG_DATA_HOME/node
export PATH="$NODE_HOME/bin:$PATH"
