#!/bin/env /bin/bash

[[ -f "${XDG_CONFIG_HOME:-$HOME/.config}/x11/xenv" ]] && source "${XDG_CONFIG_HOME:-$HOME/.config}/x11/xenv"

source /etc/profile.d/vte.sh
source $XDG_CONFIG_HOME/x11/xicons

# Don't Randomly Turn off
xset s off
xset -dpms
xset s noblank

# Speedy keys
xset r rate 210 40

# random photo every login
[[ -n $(ls -A $XDG_DATA_HOME/backgrounds 2> /dev/null) ]] && \
  feh --bg-fill --randomize $XDG_DATA_HOME/backgrounds

# Map capslock to escape
[[ "$XDG_SESSION_TYPE" == "x11" ]] && setxkbmap -option caps:escape
[[ "$XDG_SESSION_TYPE" == "wayland" ]] && gsettings set org.gnome.desktop.input-sources xkb-options "['caps:escape']"
# When caps lock is pressed only once, treat it as escape.
killall xcape 2>/dev/null ; xcape -e 'Super_L=Escape'
# Turn off caps lock if on since there is no longer a key for it.
xset -q | grep "Caps Lock:\s*on" && xdotool key Caps_Lock

# Status Bar (If this is crashing dwm, that means color emojis havne't been enabled: Install `yay -S libxft-bgra`!!!)
[[ -x /usr/local/bin/dwmblocks ]] && (pidof -s dwmblocks || dwmblocks &)

# screen lock after `-time n` minutes
[[ -x /usr/bin/xautolock && -x /usr/local/bin/slock ]] && (pidof xautolock || xautolock -time 5 -locker slock &)

# For QT Themes
# export QT_QPA_PLATFORMTHEME=qt5ct

# Compositor
[[ -x /usr/bin/picom ]] && (pidof -s picom || picom &)

# Hide mouse when typing
[[ -x /usr/bin/xbanish ]] && (pidof  -s xbanish || xbanish &)

# Screenshots
[[ -x /usr/bin/flameshot ]] && (pidof  -s flameshot || flameshot &)

# Audio
[[ -x /usr/bin/pipewire ]] && (pidof  -s pipewire || pipewire & \
  pidof  -s pipewire-pulse || pipewire-pulse & \
  pidof  -s pipewire-media-session || pipewire-media-session &)

# Bluetooth systray icon
# blueman-applet &

# Network Manager Applet
# nm-applet --indicator &

# helps with puls audio
# pasystray &

xrdb $XDG_CONFIG_HOME/x11/xresources & xrdbpid=$!
# Ensure that xrdb has finished running before moving on to start the WM/DE.
[ -n "$xrdbpid" ] && wait "$xrdbpid"
