#!/usr/bin/sh

xrandr --output DP-0 --mode 2560x1440 --rate 60 --left-of DP-4 --output DP-4 --mode 2560x1440 --rate 120

xrdb $XDG_CONFIG_HOME/x11/xresources & xrdbpid=$!

xset s off # Don't randomly turn off
xset -dpms
xset s noblank
xset b off # Disable beep
xset r rate 195 40 # Speedy keys

setxkbmap -option caps:swapescape

dbus-update-activation-environment --systemd DISPLAY

source $XDG_CONFIG_HOME/x11/xicons &
source $XDG_CONFIG_HOME/x11/xexports

# Additional configurations
if [ -d $XDG_CONFIG_HOME/x11/conf ] ; then
 for f in $XDG_CONFIG_HOME/x11/conf/?*.sh ; do
  [ -x "$f" ] && "$f"
 done
 unset f
fi

# Ensure that xrdb has finished running before moving on to start the WM/DE.
[ -n "$xrdbpid" ] && wait "$xrdbpid"
