alias aliases='$EDITOR ~/.bash_aliases && source ~/.bash_aliases'
alias bashrc='$EDITOR ~/.bashrc && source ~/.bashrc'
alias config='/usr/bin/git --git-dir=$HOME/.config/dotfiles/ --work-tree=$HOME'
alias cp="cp -i"                          # confirm before overwriting something
alias df='df -h'                          # human-readable sizes
alias doc='cd ~/Documents'
alias docs='doc'
alias down='cd ~/Downloads'
alias fd='fd-find'
alias free='free -m'                      # show sizes in MB
alias l='ls'
alias lib="cd ~/.local/lib/ben"
alias ll='ls -lah'
alias make='make -j 32'
alias more=less
alias mpv='mpv --sid=no'
alias notes='pushd . >> /dev/null; [[ ! -d ~/Documents/notes ]] && mkdir ~/Documents/notes; cd ~/Documents/notes; $EDITOR . && popd >> /dev/null'
alias nvim='[ ! -e /usr/local/bin/nvim ] && >&2 echo -e "\033[0;31m/usr/local/bin/nvim not found. Install with \"sh ~/.local/lib/ben/neovim-install.sh\"" || /usr/local/bin/nvim'
alias nvimconfig='$EDITOR ~/.config/nvim'
alias nvimrc='$EDITOR ~/.config/nvim/init.vim'
alias passotp='pass otp code --clip'
alias profile.d='$EDITOR ~/.local/etc/profile.d && source ~/.profile'
alias profile='$EDITOR ~/.profile && source ~/.profile'
alias rsync='rsync -v'
alias src='cd ~/src'
alias tv='cd ~/Videos/tv'
alias v='$EDITOR'
alias vim='$EDITOR'
alias vimc='vimconfig'
alias vimconfig='nvimconfig'
alias vimrc='nvimrc'
alias youtube-dl='yt-dlp'
alias man="Man "
