alias lib="cd ~/.local/lib/ben"

alias bashrc='$EDITOR ~/.bashrc'
alias cdu='cd ~/src/uinta'
alias config='/usr/bin/git --git-dir=$HOME/.cfg/ --work-tree=$HOME'
alias docs='cd ~/Documents'
alias down='cd ~/Downloads'
alias l='ls'
alias ll='ls -lah'
alias make='make -j 32'
alias man='vman'
alias mpv='mpv --sid=no'
alias nvimrc='$EDITOR ~/.config/nvim/init.vim'
alias pac='pacman'
alias passotp='pass otp code --clip'
alias rsync='rsync -v'
alias src='cd ~/src'
alias tv='cd ~/Videos/tv'
alias v='$EDITOR'
alias vimide='$EDITOR ~/.config/ben/ide.vim'
alias vimrc='$EDITOR ~/.vimrc'
alias youtube-dl-a='youtube-dl -f bestaudio/best'
alias youtube-dl='youtube-dl --force-ipv4'
