set cmdheight=2
set encoding=utf-8
set hidden
set incsearch
set mouse=
set nobackup
set noerrorbells
set nohlsearch
set noshowmatch
set noswapfile
set nowrap
set number
set relativenumber
set scrolloff=3
set shiftwidth=4
set signcolumn=yes
set smartcase
set smartindent
set tabstop=4
set termguicolors
set textwidth=135
set undodir=~/.vim/undodir
set undofile
set updatetime=300
