os:
  edit: 'nvim'
  editPreset: 'nvim'

gui:
  theme:
    selectedLineBgColor:
      - underline
    selectedRangeBgColor:
      - underline

git:
  autoRefresh: false
  paging:
    colorArg: never
    pager: delta --dark --paging=never
