#!/bin/env /bin/bash

export XDG_CACHE_HOME=$HOME/.cache
export XDG_CONFIG_HOME=$HOME/.config
export XDG_DATA_HOME=$HOME/.local/share

export BROWSER=/bin/brave
export EDITOR=/bin/nvim
export PAGER=/bin/less
export VISUAL=$EDITOR
export TERMINAL=/bin/alacritty
export ZDOTDIR=$XDG_CONFIG_HOME/zsh

export PATH="$HOME/.local/bin:$PATH"

source /etc/profile.d/vte.sh
source $XDG_CONFIG_HOME/user-dirs.dirs
# source $XDG_CONFIG_HOME/x/xicons
