#!/bin/env /bin/bash

[[ -f "${XDG_CONFIG_HOME:-$HOME/.config}/x/xenv" ]] && source "${XDG_CONFIG_HOME:-$HOME/.config}/x/xenv"

xrdb $XDG_CONFIG_HOME/x/xresources & xrdbpid=$!

# Don't Randomly Turn off
xset s off
xset -dpms
xset s noblank

# Speedy keys
xset r rate 210 40

# Random Photo Every Login
feh --bg-fill --randomize ~/.local/share/backgrounds

# Monitor Config
# xrandr --auto --output DVI-D-0 --mode 2560x1440 --left-of HDMI-0
# xrandr --output DP-1 --mode 2560x1440 --rate 59.95
# xrandr --auto --output HDMI-1 --mode 2560x1440 --left-of DP-1
# bind escape to caps
[[ "${XDG_SESSION_TYPE@u}" == "X11" ]] && setxkbmap -option caps:escape
[[ "${XDG_SESSION_TYPE@u}" == "WAYLAND" ]] && gsettings set org.gnome.desktop.input-sources xkb-options "['caps:escape']"
# When caps lock is pressed only once, treat it as escape.
killall xcape 2>/dev/null ; xcape -e 'Super_L=Escape'
# Turn off caps lock if on since there is no longer a key for it.
xset -q | grep "Caps Lock:\s*on" && xdotool key Caps_Lock

# Status Bar
[[ -x /usr/local/bin/dwmblocks ]] && dwmblocks &

# lock screen after `--time n` minutes
[[ -x /usr/bin/xautolock && -x /usr/local/bin/slock ]] && xautolock -time 5 -locker slock &

# For QT Themes
# export QT_QPA_PLATFORMTHEME=qt5ct

# Compositor
[[ -x /usr/bin/picom ]] && picom &

# Hide mouse when typing
[[ -x /usr/bin/xbanish ]] && xbanish &

# Screenshots
[[ -x /usr/bin/flameshot ]] && flameshot &

# Audio
[[ -x /usr/bin/pipewire ]] && pipewire & \
  pipewire-pulse & \
  pipewire-media-session &

# Bluetooth systray icon
# blueman-applet &

# Network Manager Applet
# nm-applet --indicator &

# helps with puls audio
# pasystray &

# Ensure that xrdb has finished running before moving on to start the WM/DE.
[ -n "$xrdbpid" ] && wait "$xrdbpid"
