#!/bin/zsh

export CUDA_CACHE_PATH=$XDG_CACHE_HOME/nv
export GNUPGHOME=$XDG_DATA_HOME/gnupg
export GOPATH=$XDG_DATA_HOME/go
export HISTCONTROL=ignoreboth
export JAVA_HOME=/usr/lib/jvm/default
export LESSHISTFILE="-"
export MANPAGER='nvim +Man!'
export MANWIDTH=999
export MAVEN_HOME=/opt/maven
export PASSWORD_STORE_DIR=$XDG_CONFIG_HOME/password-store
export ZPLUGINS=$XDG_CACHE_HOME/zsh/plugins

# removing the `.nv` directory from the home directory (see https://bbs.archlinux.org/viewtopic.php?id=166814):
export __GL_SHADER_DISK_CACHE_PATH=$XDG_DATA_HOME/nvidia

export CARGO_HOME=$XDG_DATA_HOME/cargo
export PATH="$CARGO_HOME/bin:$PATH"

export GEM_HOME=$XDG_DATA_HOME/ruby/gem
export PATH="$GEM_HOME/bin:$PATH"

export NODE_HOME=$XDG_DATA_HOME/node
export PATH="$NODE_HOME/bin:$PATH"

# This is the list for lf icons:
export LF_ICONS="di=📁:\
fi=📃:\
tw=🤝:\
ow=📂:\
ln=⛓:\
or=❌:\
ex=🎯:\
*.txt=✍:\
*.mom=✍:\
*.me=✍:\
*.ms=✍:\
*.png=🖼:\
*.webp=🖼:\
*.ico=🖼:\
*.jpg=📸:\
*.jpe=📸:\
*.jpeg=📸:\
*.gif=🖼:\
*.svg=🗺:\
*.tif=🖼:\
*.tiff=🖼:\
*.xcf=🖌:\
*.html=🌎:\
*.xml=📰:\
*.gpg=🔒:\
*.css=🎨:\
*.pdf=📚:\
*.djvu=📚:\
*.epub=📚:\
*.csv=📓:\
*.xlsx=📓:\
*.tex=📜:\
*.md=📘:\
*.r=📊:\
*.R=📊:\
*.rmd=📊:\
*.Rmd=📊:\
*.m=📊:\
*.mp3=🎵:\
*.opus=🎵:\
*.ogg=🎵:\
*.m4a=🎵:\
*.flac=🎼:\
*.wav=🎼:\
*.mkv=🎥:\
*.mp4=🎥:\
*.webm=🎥:\
*.mpeg=🎥:\
*.avi=🎥:\
*.mov=🎥:\
*.mpg=🎥:\
*.wmv=🎥:\
*.m4b=🎥:\
*.flv=🎥:\
*.zip=📦:\
*.rar=📦:\
*.7z=📦:\
*.tar.gz=📦:\
*.z64=🎮:\
*.v64=🎮:\
*.n64=🎮:\
*.gba=🎮:\
*.nes=🎮:\
*.gdi=🎮:\
*.1=ℹ:\
*.nfo=ℹ:\
*.info=ℹ:\
*.log=📙:\
*.iso=📀:\
*.img=📀:\
*.bib=🎓:\
*.ged=👪:\
*.part=💔:\
*.torrent=🔽:\
*.jar=♨:\
*.java=♨:\
"

