#!/bin/sh

b_tryPopd() { [[ $(dirs | wc -w) > 1 ]] && popd }
b_pushdIfNotHome() { [[ "$PWD" != "$HOME" ]] && pushd $PWD }
b_doSrc() { b_pushdIfNotHome; cd ~/.local/src/$1; }

alias aliases="$EDITOR $ZDOTDIR/zsh-aliases && source $ZDOTDIR/.zshrc"
alias bin="b_pushdIfNotHome ; cd ~/.local/bin"
alias cp="cp -i"
alias df="df -h"
alias dots="b_pushdIfNotHome ; cd ~/.dotfiles"
alias egrep="egrep --colour=auto"
alias fgrep="fgrep --colour=auto"
alias grep="grep --colour=auto"
alias lf="lfub"
alias lg="lazygit"
alias ll="ls -lah"
alias ls="ls --color=auto"
alias make="make -j32"
alias mpv="mpv --sid=no"
alias src="b_doSrc"
alias trash="trash --trash-dir=/tmp/trash"
alias ud="b_pushdIfNotHome ; cd ~/.local/src/uinta"
alias vim=$EDITOR
alias vimc="vimd && $EDITOR && b_tryPopd"
alias vimd="b_pushdIfNotHome ; cd $XDG_CONFIG_HOME/nvim"
alias wget="wget --no-hsts"
alias zrc="b_pushdIfNotHome ; cd $ZDOTDIR && $EDITOR && b_tryPopd"
