#!/usr/bin/env /usr/bin/zsh

# internal exports:
export EDITOR=nvim
export REPOS="$XDG_DATA_HOME/repos"
export UINTA_DIR="$REPOS/uinta"

# external exports:
export GNUPGHOME="$XDG_CONFIG_HOME/gnupg"
export GOMODCACHE="$XDG_CACHE_HOME/go/mod"
export GOPATH="$XDG_DATA_HOME/go"
export MAKEFLAGS="-j$(nproc)"
export NPM_CONFIG_USERCONFIG="$XDG_CACHE_HOME/npm/npmrc"
export PASSWORD_STORE_DIR="$REPOS/password-store"
export PATH="$HOME/.local/bin:$PATH"

[[ -d $REPOS/dotfiles ]] && export PATH="$REPOS/dotfiles/.local/bin:$PATH"
