#!/usr/bin/env /usr/bin/zsh

# internal exports:
export EDITOR=nvim
export REPOS="$XDG_DATA_HOME/repos"
export UINTA_DIR="$REPOS/uinta"

# external exports:
export CARGO_HOME="$XDG_CACHE_HOME/cargo"
export CUDA_CACHE_PATH="$XDG_CACHE_HOME/nv"
export GNUPGHOME="$XDG_CONFIG_HOME/gnupg"
export GOMODCACHE="$XDG_CACHE_HOME/go/mod"
export GOPATH="$XDG_DATA_HOME/go"
export NPM_CONFIG_USERCONFIG="$XDG_CACHE_HOME/npm/npmrc"
export PASSWORD_STORE_DIR="$REPOS/password-store"
export PATH="$HOME/.local/bin:$PATH"
