#!/usr/bin/zsh

export EDITOR=nvim
export GNUPGHOME="$XDG_CONFIG_HOME/gnupg"
export GOMODCACHE="$XDG_CACHE_HOME/go/mod"
export GOPATH="$XDG_DATA_HOME/go"
export NPM_CONFIG_USERCONFIG="$XDG_CACHE_HOME/npm/npmrc"
export PASSWORD_STORE_DIR="$HOME/.local/share/repos/password-store"
