#!/usr/bin/zsh

if [ "$TERM" = "linux" ]; then
  kmap_path=$XDG_RUNTIME_DIR/caps_esc_map.kmap
  if [ ! -f $kmap_path ]; then
    echo "keycode 1 = Caps_Lock" >$kmap_path
    echo "keycode 58 = Escape" >>$kmap_path
  fi
  echo ":: Swapping caps lock and escape"
  sudo -n loadkeys $kmap_path
fi
